# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newgui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(QtWidgets.QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                         QtWidgets.QSizePolicy.Expanding))
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 960, 595))
        self.tabWidget.setObjectName("tabWidget")
        self.button = QtWidgets.QToolButton()
        self.button.setToolTip('Add New Tab')
        self.button.setIcon(self.style().standardIcon(
            QtWidgets.QStyle.SP_DialogYesButton))
        self.tabWidget.setCornerWidget(self.button, QtCore.Qt.TopRightCorner)
        
        
        
        #######################RUN TAB#############################
        self.RunTab = QtWidgets.QWidget()
        self.RunTab.setObjectName("RunTab")
        self.runVerticalControlLayout = QtWidgets.QWidget(self.RunTab)
        self.runVerticalControlLayout.setGeometry(QtCore.QRect(0, 150, 160, 161))
        self.runVerticalControlLayout.setObjectName("runVerticalControlLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.runVerticalControlLayout)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.AllLabel = QtWidgets.QLabel(self.runVerticalControlLayout)
        self.AllLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AllLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AllLabel.setObjectName("AllLabel")
        self.verticalLayout_5.addWidget(self.AllLabel)
        self.HomeAll = QtWidgets.QPushButton(self.runVerticalControlLayout)
        self.HomeAll.setObjectName("HomeAll")
        self.verticalLayout_5.addWidget(self.HomeAll)
        self.StopAll = QtWidgets.QPushButton(self.runVerticalControlLayout)
        self.StopAll.setObjectName("StopAll")
        self.verticalLayout_5.addWidget(self.StopAll)
        self.DisconnectAll = QtWidgets.QPushButton(self.runVerticalControlLayout)
        self.DisconnectAll.setObjectName("DisconnectAll")
        self.verticalLayout_5.addWidget(self.DisconnectAll)
        self.RunAll = QtWidgets.QPushButton(self.runVerticalControlLayout)
        self.RunAll.setObjectName("RunAll")
        self.verticalLayout_5.addWidget(self.RunAll)
        self.img = QtWidgets.QLabel(self.RunTab)
        self.img.setGeometry(QtCore.QRect(0, 0, 791, 151))
        self.img.setObjectName("img")
        self.runVerticalControlLayout_2 = QtWidgets.QWidget(self.RunTab)
        self.runVerticalControlLayout_2.setGeometry(QtCore.QRect(170, 150, 611, 121))
        self.runVerticalControlLayout_2.setObjectName("runVerticalControlLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.runVerticalControlLayout_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.GroupName1 = QtWidgets.QLabel(self.runVerticalControlLayout_2)
        self.GroupName1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.GroupName1.setAlignment(QtCore.Qt.AlignCenter)
        self.GroupName1.setObjectName("GroupName1")
        self.horizontalLayout_3.addWidget(self.GroupName1)
        self.Group1coord = QtWidgets.QLabel(self.runVerticalControlLayout_2)
        self.Group1coord.setAlignment(QtCore.Qt.AlignCenter)
        self.Group1coord.setObjectName("Group1coord")
        self.horizontalLayout_3.addWidget(self.Group1coord)
        self.Group1edit = QtWidgets.QPushButton(self.runVerticalControlLayout_2)
        self.Group1edit.setObjectName("Group1edit")
        self.horizontalLayout_3.addWidget(self.Group1edit)
        self.Group1Run = QtWidgets.QPushButton(self.runVerticalControlLayout_2)
        self.Group1Run.setObjectName("Group1Run")
        self.horizontalLayout_3.addWidget(self.Group1Run)
        self.progressBar = QtWidgets.QProgressBar(self.runVerticalControlLayout_2)
        self.progressBar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.GroupName2 = QtWidgets.QLabel(self.runVerticalControlLayout_2)
        self.GroupName2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.GroupName2.setAlignment(QtCore.Qt.AlignCenter)
        self.GroupName2.setObjectName("GroupName2")
        self.horizontalLayout_4.addWidget(self.GroupName2)
        self.Group2coord = QtWidgets.QLabel(self.runVerticalControlLayout_2)
        self.Group2coord.setAlignment(QtCore.Qt.AlignCenter)
        self.Group2coord.setObjectName("Group2coord")
        self.horizontalLayout_4.addWidget(self.Group2coord)
        self.Group2edit = QtWidgets.QPushButton(self.runVerticalControlLayout_2)
        self.Group2edit.setObjectName("Group2edit")
        self.horizontalLayout_4.addWidget(self.Group2edit)
        self.Group2Run = QtWidgets.QPushButton(self.runVerticalControlLayout_2)
        self.Group2Run.setObjectName("Group2Run")
        self.horizontalLayout_4.addWidget(self.Group2Run)
        self.progressBar_2 = QtWidgets.QProgressBar(self.runVerticalControlLayout_2)
        self.progressBar_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.horizontalLayout_4.addWidget(self.progressBar_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.RunTab, "")
#####################################TAB 1###################################################################
        
        # self.tab = QtWidgets.QWidget()
        # self.tab.setObjectName("tab")
        # self.groupBox = QtWidgets.QGroupBox(self.tab)
        # self.groupBox.setGeometry(QtCore.QRect(0, 0, 942, 553))
        # self.groupBox.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
        #                                  QtWidgets.QSizePolicy.MinimumExpanding))
        # self.groupBox.setTitle("")
        # self.groupBox.setObjectName("groupBox")
        # self.groupBox.setContentsMargins(1, 1, 1, 1)

        # self.groupBox.setFlat(True);


        # self.mainHorizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        # self.mainHorizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 940, 321))
        # self.mainHorizontalLayoutWidget.setObjectName("mainHorizontalLayoutWidget")
        # self.mainHorizontalLayout = QtWidgets.QHBoxLayout(self.mainHorizontalLayoutWidget)
        # self.mainHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        # self.mainHorizontalLayout.setObjectName("mainHorizontalLayout")


        # self.mainVerticalLayout = QtWidgets.QVBoxLayout()
        # self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        # self.divide = QtWidgets.QFrame(self.mainHorizontalLayoutWidget)
        # self.divide.setFrameShape(QtWidgets.QFrame.HLine)
        # self.divide.setFrameShadow(QtWidgets.QFrame.Sunken)
        # self.divide.setObjectName("divide")
        # self.mainVerticalLayout.addWidget(self.divide)
        # self.firstButtonHLayout = QtWidgets.QHBoxLayout()
        # self.firstButtonHLayout.setObjectName("firstButtonHLayout")
        # self.configButtonVLayout = QtWidgets.QVBoxLayout()
        # self.configButtonVLayout.setObjectName("configButtonVLayout")
        # self.STOP = QtWidgets.QPushButton(self.mainHorizontalLayoutWidget)
        # self.STOP.setObjectName("STOP")
        # self.configButtonVLayout.addWidget(self.STOP)
        # self.load = QtWidgets.QPushButton(self.mainHorizontalLayoutWidget)
        # self.load.setObjectName("load")
        # self.configButtonVLayout.addWidget(self.load)
        # self.create = QtWidgets.QPushButton(self.mainHorizontalLayoutWidget)
        # self.create.setObjectName("create")
        # self.configButtonVLayout.addWidget(self.create)
        # self.run = QtWidgets.QPushButton(self.mainHorizontalLayoutWidget)
        # self.run.setObjectName("run")
        # self.configButtonVLayout.addWidget(self.run)
        # self.firstButtonHLayout.addLayout(self.configButtonVLayout)
        # self.line = QtWidgets.QFrame(self.mainHorizontalLayoutWidget)
        # self.line.setFrameShape(QtWidgets.QFrame.VLine)
        # self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        # self.line.setObjectName("line")
        # self.firstButtonHLayout.addWidget(self.line)
        # self.displayLayout = QtWidgets.QVBoxLayout()
        # self.displayLayout.setObjectName("displayLayout")
        # self.PositionLabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        # self.PositionLabel.setObjectName("PositionLabel")
        # self.displayLayout.addWidget(self.PositionLabel)
        # self.VelocityLabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        # self.VelocityLabel.setObjectName("VelocityLabel")
        # self.displayLayout.addWidget(self.VelocityLabel)
        # self.firstButtonHLayout.addLayout(self.displayLayout)
        # self.mainVerticalLayout.addLayout(self.firstButtonHLayout)
        # self.hl = QtWidgets.QHBoxLayout()
        # self.hl.setObjectName("hl")
        # self.inputgrid = QtWidgets.QGridLayout()
        # self.inputgrid.setSpacing(1)
        # self.inputgrid.setObjectName("inputgrid")
        # self.ycoordlabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        # self.ycoordlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        # self.ycoordlabel.setAlignment(QtCore.Qt.AlignCenter)
        # self.ycoordlabel.setObjectName("ycoordlabel")
        # self.inputgrid.addWidget(self.ycoordlabel, 0, 1, 1, 1)
        # self.zspeedlabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        # self.zspeedlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        # self.zspeedlabel.setAlignment(QtCore.Qt.AlignCenter)
        # self.zspeedlabel.setObjectName("zspeedlabel")
        # self.inputgrid.addWidget(self.zspeedlabel, 2, 2, 1, 1)
        # self.xspeedlabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        # self.xspeedlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        # self.xspeedlabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        # self.xspeedlabel.setAlignment(QtCore.Qt.AlignCenter)
        # self.xspeedlabel.setObjectName("xspeedlabel")
        # self.inputgrid.addWidget(self.xspeedlabel, 2, 0, 1, 1)
        # self.yspeedlabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        # self.yspeedlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        # self.yspeedlabel.setAlignment(QtCore.Qt.AlignCenter)
        # self.yspeedlabel.setObjectName("yspeedlabel")
        # self.inputgrid.addWidget(self.yspeedlabel, 2, 1, 1, 1)
        # self.zcoord = QtWidgets.QLineEdit(self.mainHorizontalLayoutWidget)
        # self.zcoord.setObjectName("zcoord")
        # self.inputgrid.addWidget(self.zcoord, 1, 2, 1, 1)
        # self.ycoord = QtWidgets.QLineEdit(self.mainHorizontalLayoutWidget)
        # self.ycoord.setObjectName("ycoord")
        # self.inputgrid.addWidget(self.ycoord, 1, 1, 1, 1)
        # self.xspeed = QtWidgets.QLineEdit(self.mainHorizontalLayoutWidget)
        # self.xspeed.setObjectName("xspeed")
        # self.inputgrid.addWidget(self.xspeed, 3, 0, 1, 1)
        # self.yspeed = QtWidgets.QLineEdit(self.mainHorizontalLayoutWidget)
        # self.yspeed.setObjectName("yspeed")
        # self.inputgrid.addWidget(self.yspeed, 3, 1, 1, 1)
        # self.xcoord = QtWidgets.QLineEdit(self.mainHorizontalLayoutWidget)
        # self.xcoord.setObjectName("xcoord")
        # self.inputgrid.addWidget(self.xcoord, 1, 0, 1, 1)
        # self.zspeed = QtWidgets.QLineEdit(self.mainHorizontalLayoutWidget)
        # self.zspeed.setObjectName("zspeed")
        # self.inputgrid.addWidget(self.zspeed, 3, 2, 1, 1)
        # self.zcoordlabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        # self.zcoordlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        # self.zcoordlabel.setAlignment(QtCore.Qt.AlignCenter)
        # self.zcoordlabel.setObjectName("zcoordlabel")
        # self.inputgrid.addWidget(self.zcoordlabel, 0, 2, 1, 1)
        # self.xcoordlabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        # self.xcoordlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        # self.xcoordlabel.setAlignment(QtCore.Qt.AlignCenter)
        # self.xcoordlabel.setObjectName("xcoordlabel")
        # self.inputgrid.addWidget(self.xcoordlabel, 0, 0, 1, 1)
        # self.hl.addLayout(self.inputgrid)
        # self.segment = QtWidgets.QFrame(self.mainHorizontalLayoutWidget)
        # self.segment.setFrameShape(QtWidgets.QFrame.VLine)
        # self.segment.setFrameShadow(QtWidgets.QFrame.Sunken)
        # self.segment.setObjectName("segment")
        # self.hl.addWidget(self.segment)
        # self.vl = QtWidgets.QVBoxLayout()
        # self.vl.setObjectName("vl")
        # self.move = QtWidgets.QPushButton(self.mainHorizontalLayoutWidget)
        # self.move.setObjectName("move")
        # self.vl.addWidget(self.move)
        # self.set_speed = QtWidgets.QPushButton(self.mainHorizontalLayoutWidget)
        # self.set_speed.setObjectName("set_speed")
        # self.vl.addWidget(self.set_speed)
        # self.zero = QtWidgets.QPushButton(self.mainHorizontalLayoutWidget)
        # self.zero.setObjectName("zero")
        # self.vl.addWidget(self.zero)
        # self.hl.addLayout(self.vl)
        # self.mainVerticalLayout.addLayout(self.hl)
        # self.mainHorizontalLayout.addLayout(self.mainVerticalLayout)
        # self.lin = QtWidgets.QFrame(self.mainHorizontalLayoutWidget)
        # self.lin.setFrameShape(QtWidgets.QFrame.VLine)
        # self.lin.setFrameShadow(QtWidgets.QFrame.Sunken)
        # self.lin.setObjectName("lin")
        # self.mainHorizontalLayout.addWidget(self.lin)
        # self.widget = QtWidgets.QWidget(self.groupBox)
        # self.widget.setGeometry(QtCore.QRect(545, 330, 281, 211))
        # self.widget.setObjectName("widget")
        # self.groupTextLayout = QtWidgets.QVBoxLayout(self.widget)
        # self.groupTextLayout.setContentsMargins(0, 0, 0, 0)
        # self.groupTextLayout.setObjectName("groupTextLayout")
        # self.GroupLabel = QtWidgets.QLabel(self.widget)
        # self.GroupLabel.setAlignment(QtCore.Qt.AlignCenter)
        # self.GroupLabel.setObjectName("GroupLabel")
        # self.groupTextLayout.addWidget(self.GroupLabel)
        # self.GroupText = QtWidgets.QTextEdit(self.widget)
        # self.GroupText.setObjectName("GroupText")
        # self.GroupText.setReadOnly(True)
        # self.groupTextLayout.addWidget(self.GroupText)
        # self.runInfoLayout = QtWidgets.QWidget(self.groupBox)
        # self.runInfoLayout.setGeometry(QtCore.QRect(10, 330, 371, 80))
        # self.runInfoLayout.setObjectName("runInfoLayout")
        # self.infoLayout = QtWidgets.QHBoxLayout(self.runInfoLayout)
        # self.infoLayout.setContentsMargins(0, 0, 0, 0)
        # self.infoLayout.setObjectName("infoLayout")
        # self.label = QtWidgets.QLabel(self.runInfoLayout)
        # self.label.setObjectName("label")
        # self.infoLayout.addWidget(self.label)
        # self.pBar = QtWidgets.QProgressBar(self.runInfoLayout)
        # self.pBar.setProperty("value", 24)
        # self.pBar.setObjectName("pBar")
        # self.infoLayout.addWidget(self.pBar)
        # self.timelabel = QtWidgets.QLabel(self.runInfoLayout)
        # self.timelabel.setObjectName("timelabel")
        # self.infoLayout.addWidget(self.timelabel)
        # self.tabWidget.addTab(self.tab, "")
        
############################################################TAB2##################################



        # self.tab_2 = QtWidgets.QWidget()
        # self.tab_2.setObjectName("tab_2")
        # self.tabWidget.addTab(self.tab_2, "")
        
        
     
        
        
        
 ###############################################################################       
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AllLabel.setText(_translate("MainWindow", "For all connected drives"))
        self.HomeAll.setText(_translate("MainWindow", "Home All"))
        self.StopAll.setText(_translate("MainWindow", "Stop All"))
        self.DisconnectAll.setText(_translate("MainWindow", "Disconnect All"))
        self.RunAll.setText(_translate("MainWindow", "Run All"))
        self.img.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/LAPD.jpg\"/></p></body></html>"))
        self.GroupName1.setText(_translate("MainWindow", "GROUP NAME"))
        self.Group1coord.setText(_translate("MainWindow", "(x,y,z)"))
        self.Group1edit.setText(_translate("MainWindow", "Edit Config"))
        self.Group1Run.setText(_translate("MainWindow", "Run Config"))
        self.GroupName2.setText(_translate("MainWindow", "GROUP NAME"))
        self.Group2coord.setText(_translate("MainWindow", "(x,y,z)"))
        self.Group2edit.setText(_translate("MainWindow", "Edit Config"))
        self.Group2Run.setText(_translate("MainWindow", "Run Config"))
        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RunTab), _translate("MainWindow", "Run"))
        

    
    
class TabPage(QtWidgets.QWidget):
    def __init__(self, parent = None):
        super().__init__(parent)
        self.groupBox = QtWidgets.QGroupBox(self)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 942, 553))
        self.groupBox.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                         QtWidgets.QSizePolicy.MinimumExpanding))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox.setContentsMargins(1, 1, 1, 1)

        self.groupBox.setFlat(True);


        self.mainHorizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.mainHorizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 940, 321))
        self.mainHorizontalLayoutWidget.setObjectName("mainHorizontalLayoutWidget")
        self.mainHorizontalLayout = QtWidgets.QHBoxLayout(self.mainHorizontalLayoutWidget)
        self.mainHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.mainHorizontalLayout.setObjectName("mainHorizontalLayout")


        self.mainVerticalLayout = QtWidgets.QVBoxLayout()
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        self.divide = QtWidgets.QFrame(self.mainHorizontalLayoutWidget)
        self.divide.setFrameShape(QtWidgets.QFrame.HLine)
        self.divide.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.divide.setObjectName("divide")
        self.mainVerticalLayout.addWidget(self.divide)
        self.firstButtonHLayout = QtWidgets.QHBoxLayout()
        self.firstButtonHLayout.setObjectName("firstButtonHLayout")
        self.configButtonVLayout = QtWidgets.QVBoxLayout()
        self.configButtonVLayout.setObjectName("configButtonVLayout")
        self.STOP = QtWidgets.QPushButton(self.mainHorizontalLayoutWidget)
        self.STOP.setObjectName("STOP")
        self.configButtonVLayout.addWidget(self.STOP)
        self.load = QtWidgets.QPushButton(self.mainHorizontalLayoutWidget)
        self.load.setObjectName("load")
        self.configButtonVLayout.addWidget(self.load)
        self.create = QtWidgets.QPushButton(self.mainHorizontalLayoutWidget)
        self.create.setObjectName("create")
        self.configButtonVLayout.addWidget(self.create)
        self.run = QtWidgets.QPushButton(self.mainHorizontalLayoutWidget)
        self.run.setObjectName("run")
        self.configButtonVLayout.addWidget(self.run)
        self.firstButtonHLayout.addLayout(self.configButtonVLayout)
        self.line = QtWidgets.QFrame(self.mainHorizontalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.firstButtonHLayout.addWidget(self.line)
        self.displayLayout = QtWidgets.QVBoxLayout()
        self.displayLayout.setObjectName("displayLayout")
        self.PositionLabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        self.PositionLabel.setObjectName("PositionLabel")
        self.displayLayout.addWidget(self.PositionLabel)
        self.VelocityLabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        self.VelocityLabel.setObjectName("VelocityLabel")
        self.displayLayout.addWidget(self.VelocityLabel)
        self.firstButtonHLayout.addLayout(self.displayLayout)
        self.mainVerticalLayout.addLayout(self.firstButtonHLayout)
        self.hl = QtWidgets.QHBoxLayout()
        self.hl.setObjectName("hl")
        self.inputgrid = QtWidgets.QGridLayout()
        self.inputgrid.setSpacing(1)
        self.inputgrid.setObjectName("inputgrid")
        self.ycoordlabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        self.ycoordlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.ycoordlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ycoordlabel.setObjectName("ycoordlabel")
        self.inputgrid.addWidget(self.ycoordlabel, 0, 1, 1, 1)
        self.zspeedlabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        self.zspeedlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.zspeedlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zspeedlabel.setObjectName("zspeedlabel")
        self.inputgrid.addWidget(self.zspeedlabel, 2, 2, 1, 1)
        self.xspeedlabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        self.xspeedlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.xspeedlabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.xspeedlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xspeedlabel.setObjectName("xspeedlabel")
        self.inputgrid.addWidget(self.xspeedlabel, 2, 0, 1, 1)
        self.yspeedlabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        self.yspeedlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.yspeedlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yspeedlabel.setObjectName("yspeedlabel")
        self.inputgrid.addWidget(self.yspeedlabel, 2, 1, 1, 1)
        self.zcoord = QtWidgets.QLineEdit(self.mainHorizontalLayoutWidget)
        self.zcoord.setObjectName("zcoord")
        self.inputgrid.addWidget(self.zcoord, 1, 2, 1, 1)
        self.ycoord = QtWidgets.QLineEdit(self.mainHorizontalLayoutWidget)
        self.ycoord.setObjectName("ycoord")
        self.inputgrid.addWidget(self.ycoord, 1, 1, 1, 1)
        self.xspeed = QtWidgets.QLineEdit(self.mainHorizontalLayoutWidget)
        self.xspeed.setObjectName("xspeed")
        self.inputgrid.addWidget(self.xspeed, 3, 0, 1, 1)
        self.yspeed = QtWidgets.QLineEdit(self.mainHorizontalLayoutWidget)
        self.yspeed.setObjectName("yspeed")
        self.inputgrid.addWidget(self.yspeed, 3, 1, 1, 1)
        self.xcoord = QtWidgets.QLineEdit(self.mainHorizontalLayoutWidget)
        self.xcoord.setObjectName("xcoord")
        self.inputgrid.addWidget(self.xcoord, 1, 0, 1, 1)
        self.zspeed = QtWidgets.QLineEdit(self.mainHorizontalLayoutWidget)
        self.zspeed.setObjectName("zspeed")
        self.inputgrid.addWidget(self.zspeed, 3, 2, 1, 1)
        self.zcoordlabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        self.zcoordlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.zcoordlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.zcoordlabel.setObjectName("zcoordlabel")
        self.inputgrid.addWidget(self.zcoordlabel, 0, 2, 1, 1)
        self.xcoordlabel = QtWidgets.QLabel(self.mainHorizontalLayoutWidget)
        self.xcoordlabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.xcoordlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.xcoordlabel.setObjectName("xcoordlabel")
        self.inputgrid.addWidget(self.xcoordlabel, 0, 0, 1, 1)
        self.hl.addLayout(self.inputgrid)
        self.segment = QtWidgets.QFrame(self.mainHorizontalLayoutWidget)
        self.segment.setFrameShape(QtWidgets.QFrame.VLine)
        self.segment.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.segment.setObjectName("segment")
        self.hl.addWidget(self.segment)
        self.vl = QtWidgets.QVBoxLayout()
        self.vl.setObjectName("vl")
        self.move = QtWidgets.QPushButton(self.mainHorizontalLayoutWidget)
        self.move.setObjectName("move")
        self.vl.addWidget(self.move)
        self.set_speed = QtWidgets.QPushButton(self.mainHorizontalLayoutWidget)
        self.set_speed.setObjectName("set_speed")
        self.vl.addWidget(self.set_speed)
        self.zero = QtWidgets.QPushButton(self.mainHorizontalLayoutWidget)
        self.zero.setObjectName("zero")
        self.vl.addWidget(self.zero)
        self.hl.addLayout(self.vl)
        self.mainVerticalLayout.addLayout(self.hl)
        self.mainHorizontalLayout.addLayout(self.mainVerticalLayout)
        self.lin = QtWidgets.QFrame(self.mainHorizontalLayoutWidget)
        self.lin.setFrameShape(QtWidgets.QFrame.VLine)
        self.lin.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lin.setObjectName("lin")
        self.mainHorizontalLayout.addWidget(self.lin)
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(545, 330, 281, 211))
        self.widget.setObjectName("widget")
        self.groupTextLayout = QtWidgets.QVBoxLayout(self.widget)
        self.groupTextLayout.setContentsMargins(0, 0, 0, 0)
        self.groupTextLayout.setObjectName("groupTextLayout")
        self.GroupLabel = QtWidgets.QLabel(self.widget)
        self.GroupLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.GroupLabel.setObjectName("GroupLabel")
        self.groupTextLayout.addWidget(self.GroupLabel)
        self.GroupText = QtWidgets.QTextEdit(self.widget)
        self.GroupText.setObjectName("GroupText")
        self.GroupText.setReadOnly(True)
        self.groupTextLayout.addWidget(self.GroupText)
        self.runInfoLayout = QtWidgets.QWidget(self.groupBox)
        self.runInfoLayout.setGeometry(QtCore.QRect(10, 330, 371, 80))
        self.runInfoLayout.setObjectName("runInfoLayout")
        self.infoLayout = QtWidgets.QHBoxLayout(self.runInfoLayout)
        self.infoLayout.setContentsMargins(0, 0, 0, 0)
        self.infoLayout.setObjectName("infoLayout")
        self.label = QtWidgets.QLabel(self.runInfoLayout)
        self.label.setObjectName("label")
        self.infoLayout.addWidget(self.label)
        self.pBar = QtWidgets.QProgressBar(self.runInfoLayout)
        self.pBar.setProperty("value", 24)
        self.pBar.setObjectName("pBar")
        self.infoLayout.addWidget(self.pBar)
        self.timelabel = QtWidgets.QLabel(self.runInfoLayout)
        self.timelabel.setObjectName("timelabel")
        self.infoLayout.addWidget(self.timelabel)
    
        self.STOP.setText( "STOP MOVEMENT")
        self.load.setText( "LOAD GROUP CONFIGURATION")
        self.create.setText( "CREATE GROUP CONFIGURATION")
        self.run.setText( "RUN CONFIGURATION")
        self.PositionLabel.setText( "CURRENT PROBE POSITION")
        self.VelocityLabel.setText( "CURRENT MOTOR VELOCITY")
        self.ycoordlabel.setText( "Y-COORDINATE")
        self.zspeedlabel.setText( "Z-SPEED")
        self.xspeedlabel.setText( "X-SPEED")
        self.yspeedlabel.setText( "Y-SPEED")
        self.zcoordlabel.setText( "Z-COORDINATE")
        self.xcoordlabel.setText(" X-COORDINATE")
        self.move.setText("Move")
        self.set_speed.setText( "Set Speed")
        self.zero.setText( "Set Zero")
        self.GroupLabel.setText( "Group Information")
        self.label.setText( "RUN PROGRESS")
        self.timelabel.setText("Estimated Time Left:")
      
        
        
    
    
    
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

